### ISSUE TITLE
PPDiffusers可以加载SDXL1.0模型吗？

### ISSUE THREAD

**Issue by peteli25** [PaddlePaddle/PaddleMIX#117]
PPDiffusers可以加载SDXL1.0模型吗？

**Comment by westfish** [comment]
目前develop已经支持

**Comment by dddlli** [comment]
ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 2048But received Y'dims[0] is 768
  [Hint: Expected y_dims[y_ndim - 2] == K, but received y_dims[y_ndim - 2]:768 != K:2048.] (at ../paddle/phi/kernels/impl/matmul_kernel_impl.h:324)
  [operator < linear > error]
