### ISSUE TITLE
add some example

### ISSUE THREAD

**Issue by CrazyBoyM** [PaddlePaddle/PaddleMIX#187]
text_to_image_generation-stable_diffusion_xl
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/d72729f9-8685-48f9-a238-e4ddf6d264f3)

text_to_image_generation-kandinsky2_2
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/188f76dd-4bd7-4a33-8f30-b893c7a9e249)

text_to_image_generation-unidiffuser
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/a6eb11d2-ad27-4263-8cb4-b0d8dd42b36c)

image_to_image_text_guided_generation-stable_diffusion_xl
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/41bd9381-2799-4bed-a5e2-ba312a2f8da9)
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/db672d03-2e3a-46ac-97fd-d80cca18dbbe)

image_to_image_text_guided_generation-kandinsky2_2
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/aae57109-94ad-408e-ae75-8cce650cebe5)
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/23cf2c4e-416f-4f21-82a6-e57de11b5e83)

text_guided_image_inpainting-kandinsky2_2
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/64a943d5-167b-4433-91c3-3cf9279714db)
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/f469c127-52f4-4173-a693-c06b92a052aa)

**Comment by CrazyBoyM** [comment]
text_to_image_generation-sdxl_base_with_refiner
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/8ef36826-ed94-4856-a356-af1677f60d1b)

text_to_video_generation-synth with zeroscope_v2_576w
![sdvideo](https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/0347b61a-cf7e-4cbb-b684-485055a3e516)


text_to_video_generation-synth with zeroscope_v2_XL
![text_to_video_generation-synth-result-astronaut_riding_a_horse (2)]
(https://github.com/PaddlePaddle/PaddleMIX/assets/35400185/43ebbca0-9f07-458b-809a-acf296a2539b)

**Comment by westfish** [comment]
text_to_video_generation-lvdm-result-ddim_lvdm_text_to_video_ucf_000_1x16x256x256x3
![mbfpx-r08w7](https://github.com/PaddlePaddle/PaddleMIX/assets/20476674/2b9d53c1-0272-4c7a-81b2-cd962d23bbee)
