### ISSUE TITLE
转torch权重为paddle权重时没有转换Linear层的weight，想问下怎么不用transpose

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleMIX#239]
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/ppdiffusers/utils/load_utils.py

转torch权重为paddle权重时没有转换Linear层的weight，想问下怎么不用transpose，在nn.Linear 的weight上，torch和paddle不是需要transpose吗
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/f47edcc8-e992-4fc0-9a7f-3dc2ab327d58)

**Comment by JunnYu** [comment]
你好，这里的代码主要是为了加载权重，即将torch权重加载成paddle类型的，这里还不会涉及 nn.Linear 的权重转置
