### ISSUE TITLE
新增音频生成图像（Audio-to-Image Generation）

### ISSUE THREAD

**Issue by chenjjcccc** [PaddlePaddle/PaddleMIX#258]
# 新增音频生成图像（Audio-to-Image Generation）
### 任务背景
- 为音乐生成应用新增gradio demo。
参考[Gradio应用介绍](https://aistudio.baidu.com/projectdetail/6536645)和 [image-to-music_AI应用-飞桨AI Studio星河社区](https://aistudio.baidu.com/application/detail/7515)。
### 完成步骤
1. 将已接入的应用添加gradio demo，音频生成图像（Audio-to-Image Generation [代码链接](https://github.com/PaddlePaddle/PaddleMIX/blob/develop/applications/Audio2Img/README.md/#audio-to-image)。
2. 输入为三种：
    * 音频
    * 音频+文本
    * 音频+图像。
3. 输出为图像。
### 提交内容：
1. 脚本提交到[PaddleMix](脚本提交到PaddleMix)

**Comment by shiyutang** [comment]
已经在 #365 中完成
