### ISSUE TITLE
PaddleMIX ppdiffusers中models模块升级unet相关代码

### ISSUE THREAD

**Issue by chenjjcccc** [PaddlePaddle/PaddleMIX#264]
# PaddleMIX ppdiffusers中models模块升级unet相关代码
### 任务背景
- models模块代码升级。
- 升级脚本：
  * models/unet_1d.py
  * models/unet_2d.py
  * models/unet_2d_blocks.py
  * models/unet_2d_condition.py
  * models/unet_3d_condition.py
### 完成步骤
1. 对比ppdiffusers (v0.19.3)和diffusers (v0.21.1)的代码差异，可使用[页面diff工具](https://github.com/huggingface/diffusers/compare/v0.19.3...v0.21.1)。
2. fork [PaddleMix](https://github.com/PaddlePaddle/PaddleMIX)仓库并对题目中提到的代码文件进行更新
3. 学习掌握pytest测试工具的使用，并确保升级后的代码文件能够通过tests/models目录下的单元测试用例（如有单测代码更新需要先进行对应单测升级再测试），确保升级后的代码正确。
4. 提交PR到主仓库的develop分支，并描述任务具体完成情况（附上测试信息、推理用例）
### 提交内容：
1. 升级后的代码文件。
2. 测试情况。

### 题目更新：
> 1. 对比ppdiffusers (v0.19.3)和diffusers (v0.21.1)的代码差异，可使用[页面diff工具](https://github.com/huggingface/diffusers/compare/v0.19.3...v0.21.1)

当前还请按照diffusers最新稳定版本0.23.1更新升级

**Comment by shiyutang** [comment]
任务已完成 by @co63oc ，close issue。
