### ISSUE TITLE
Kandinsky2.2 训练支持

### ISSUE THREAD

**Issue by chenjjcccc** [PaddlePaddle/PaddleMIX#268]
# Kandinsky2.2 训练支持
### 任务背景
- PaddleMIX ppdiffusers新增kandinsky2_2训练流程。
### 完成步骤
1. 参考[代码](https://github.com/huggingface/diffusers/tree/main/examples/kandinsky2_2/text_to_image)完成对齐
### 提交内容：
1. 提交到[目录](https://github.com/PaddlePaddle/PaddleMIX/tree/develop/ppdiffusers/examples)

**Comment by shiyutang** [comment]
close due to https://github.com/PaddlePaddle/PaddleMIX/pull/378.
