### ISSUE TITLE
ppdiffusers/examples/community的ControlNet Reference Only 示例代码报错

### ISSUE THREAD

**Issue by flychord** [PaddlePaddle/PaddleMIX#274]
ppdiffusers/examples/community的ControlNet Reference Only 示例代码报错TypeError: transformer_2d_model_forward() got an unexpected keyword argument 'attention_mask'，请问这个怎么解决
![paddlemix_报错](https://github.com/PaddlePaddle/PaddleMIX/assets/40018612/1a7f8da2-2526-42ab-bbe3-e888c06af688)

**Comment by JunnYu** [comment]
你好，现在已经修复问题了，可以直接使用了
