### ISSUE TITLE
lvdm_text2video运行错误  TypeError: Descriptors cannot be created directly.

### ISSUE THREAD

**Issue by lrjxgl** [PaddlePaddle/PaddleMIX#302]
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by westfish** [comment]
protobuf版本不兼容，可以尝试pip install protobuf==3.20.x降级包
