### ISSUE TITLE
请问paddle的GroundDino模型和pytorch的GroundDino模型之间是做了某种转换吗？

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleMIX#349]
@LokeZhou  老哥下午好，请问paddle的GroundDino模型和pytorch的GroundDino模型之间是做了某种转换吗？
我使用另一个基于pytorch的微调GroundDino的工程中微调了一个模型后，我想将之迁移至paddle框架，并使用静态模型，在C++端推理，我采用的转换的方式如下
1. 直接读取paddle和pytorch的两个模型
2. 通过“state_dict”接口，获取各个子模块的key的value（很幸运，我发现paddle和pytorch在key的命名上是一致的）
3. 对网络的每个模块按照key进行赋值转换
4. 重新使用“set_state_dict”接口填充paddle模型的参数

上述操作成功了，并且我也能使用转换后的模型成功导出静态图。但是模型的推理结果很异常，近乎是无法使用的，为此我进一步排查了paddle的GroundDino模型和pytorch的GroundDino模型的参数，然后发现貌似这两个模型存在参数值的不同

下图是我用对比工具对比的结果，模型结构是一样的，但是内里的参数值不同，并且我找不出规律，唯一的规律就是偏置（bias）层的参数是完全一致的
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/28993936/847b83d0-30fd-4068-8bff-3a4e15e0238b)

我想问问，这其中有什么转换的规律吗？因为我使用paddle的模型也能正常出结果，使用pytorch也能正常，唯独使用我自己转换的模型会有问题

**Comment by LokeZhou** [comment]
感谢关注与使用，需要注意的是，paddle与pytorch的Linear层，权重是转置关系，需要用weight.T转换，然后赋值。另外，可以逐层或二分的方法，输出paddle与pytorch相同层的比较，看看是否对齐，或者定位哪一层没对齐。若想更深入对齐，可使用我们的对齐工具：https://github.com/PaddlePaddle/PaDiff
