### ISSUE TITLE
thrust::system::system_error 问题

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleMIX#360]
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/tomesd/README.md
```
import paddle
from ppdiffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", safety_checker=None, paddle_dtype=paddle.float16)

# 我们可以开启 xformers
# pipe.enable_xformers_memory_efficient_attention()

# Apply ToMe with a 50% merging ratio
pipe.apply_tome(ratio=0.5) # Can also use pipe.unet in place of pipe here

generator = paddle.Generator().manual_seed(0)
image = pipe("a photo of an astronaut riding a horse on mars", generator=generator).images[0]
image.save("astronaut.png")
```

运行错误 thrust::system::system_error，如果注释 pipe.apply_tome 可以运行
ppdiffusers为git develop版本

![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/deb7109e-21d6-4912-8c79-159ab9084d31)

**Comment by JunnYu** [comment]
你好，可以提供一下paddle版本、然后ppdiffusers版本，我这里复现一下，感觉可能是paddle版本升级导致可能某些算子不一样了导致的问题

**Comment by co63oc** [comment]
现在测试没有问题了

**Comment by JunnYu** [comment]
你好，你这个当时是怎么解决的？我现在也碰到相同的问题了

**Comment by co63oc** [comment]
> 你好，你这个当时是怎么解决的？我现在也碰到相同的问题了

paddle, paddlenlp, paddlemix都用develop版本，然后测试可以了,  python 是3.10，不确定是不是python版本有影响
