### ISSUE TITLE
'Namespace' object has no attribute 'report_to'

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleMIX#361]
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/unconditional_image_generation/README.md

```
python -u -m paddle.distributed.launch --gpus "0"  train_unconditional.py \
  --dataset_name="huggan/flowers-102-categories" \
  --cache_dir 'data' \
  --resolution=64 --center_crop --random_flip \
  --output_dir="ddpm-ema-flowers-64" \
  --train_batch_size=16 \
  --num_epochs=100 \
  --gradient_accumulation_steps=1 \
  --use_ema \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500
```
运行到1000时错误
'Namespace' object has no attribute 'report_to'

![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/452e8bb4-5ffb-44d3-aa55-31136925b6e3)

**Comment by JunnYu** [comment]
这是一个bug，写的时候argument parser没有加report_to，你可以提一个PR修复一下
