### ISSUE TITLE
train_lvdm_short.py测试运行错误

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleMIX#362]
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/text_to_video_lvdm/README.md

![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/d2e30f37-0765-49d4-aada-ba765982de35)
```
python -u train_lvdm_short.py
```
运行提示没有output_dir参数
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/c6a6b63c-eef3-4e9e-89ea-75259485d628)

增加output_dir参数后运行错误是url不存在
```
python -u train_lvdm_short.py --output_dir out
```
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/0a90271d-d8d1-491e-b062-dd4f9b1e4a01)

**Comment by westfish** [comment]
参考这个 https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/text_to_video_lvdm/scripts/train_lvdm_short_sky.sh

**Comment by co63oc** [comment]
@westfish 

下载了数据集到目录 /data/lvdm/sky/train/
https://github.com/m-bain/webvid

[train](http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_train.csv) (640MB) wget http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_train.csv
[val](http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv) (1.3MB) wget http://www.robots.ox.ac.uk/~maxbain/webvid/results_2M_val.csv

运行
```
bash PaddleMIX/ppdiffusers/examples/text_to_video_lvdm/scripts/train_lvdm_text2video_webvid.sh
```

返回错误 ValueError: '4' is not in list
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/1d74082d-e5eb-46cf-b117-93663bfff540)

**Comment by westfish** [comment]
你跑最新版本的吧，不过这个目前还没有发版https://github.com/PaddlePaddle/PaddleMIX/tree/upgrade_ppdiffusers0240/ppdiffusers/examples/text_to_video_lvdm

**Comment by co63oc** [comment]
@westfish 
用upgrade_ppdiffusers0240分支一样的错误，信息不能确定是哪里的问题
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/f85c8bed-44c3-4869-8025-42213e5a3b4a)
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/a8a27325-6ce9-467f-9043-dc8fc55a257d)

应该是可以运行的，不知道是哪里设置不对

**Comment by westfish** [comment]
你跑的是多卡程序，有足够多的卡吗？跑过单卡吗，有问题吗？

**Comment by co63oc** [comment]
> 你跑的是多卡程序，有足够多的卡吗？跑过单卡吗，有问题吗？

修改了配置可以运行
