### ISSUE TITLE
subtract不支持 int8类型

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleMIX#399]
upgrade_ppdiffusers0240 分支
进入目录 ppdiffusers/deploy/controlnet
运行
```
python infer.py --scheduler "ddim" --backend paddle --task text2img_control
```

![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/bac7dfee-99b5-4b2c-bc8d-cf22a3da68de)

提示subtract不支持 int8类型

paddle, paddlenlp, paddlemix为develop版本

**Comment by JunnYu** [comment]
正常是不会得到int8的输出类型的，这是哪里跑的时候碰到错误了吗？

**Comment by co63oc** [comment]
运行的命令然后返回的错误
```
python infer.py --scheduler "ddim" --backend paddle --task text2img_control
```

**Comment by westfish** [comment]
可以试试develop版paddle，upgrade_ppdiffusers0240还在开发中，deploy会有些不稳定的因素
