### ISSUE TITLE
 NameError: name 'method' is not defined

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleMIX#400]
upgrade_ppdiffusers0240 分支
进入ppdiffusers/deploy/ipadapter/sd15目录运行
```
python export_model.py --pretrained_model_name_or_path runwayml/stable-diffusion-v1-5 --ipadapter_pretrained_model_name_or_path h94/IP-Adapter --ipadapter_model_subfolder models --ipadapter_weight_name ip-adapter_sd15.safetensors --output_path static_model/stable-diffusion-v1-5-ipadapter
```
返回错误  NameError: name 'method' is not defined
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/55fdcb36-5257-4157-a44a-6b521aaae87f)

paddle, paddlenlp, paddlemix为develop版本

**Comment by JunnYu** [comment]
你好，这个已经有PR在修了，https://github.com/PaddlePaddle/PaddleMIX/pull/402
