### ISSUE TITLE
open-sora 推理复现

### ISSUE THREAD

**Issue by LokeZhou** [PaddlePaddle/PaddleMIX#487]
# 新增模型open-sora
### 任务背景
- open-sora是一个开源的文生视频模型，该任务只需复现前向推理流程即可。
### 完成步骤
1. 模型、代码已经开源。
2. 根据开源代码进行网络结构转换，推理，[代码链接](https://github.com/hpcaitech/Open-Sora.git)。
3. 前向推理跑通对齐即可，可参考[inference](https://github.com/hpcaitech/Open-Sora/tree/main?tab=readme-ov-file#inference)。
4. 提交代码PR到[PaddleMIX](https://github.com/PaddlePaddle/PaddleMIX/tree/develop)。

参考PR：https://github.com/PaddlePaddle/PaddleMIX/pull/401
### 提交内容：
1. 提交代码到[目录](https://github.com/PaddlePaddle/PaddleMIX/tree/develop/ppdiffusers/examples)

**Comment by nemonameless** [comment]
权重以Open-Sora 1.0或1.1均可，尽可能以1.1为准。

**Comment by Tsaiyue** [comment]
Done by https://github.com/PaddlePaddle/PaddleMIX/pull/537
