### ISSUE TITLE
分段故障。 Segmentation Fault

### ISSUE THREAD

**Issue by Tortoise17** [PaddlePaddle/PaddleMIX#517]
https://github.com/PaddlePaddle/PaddleMIX/tree/develop/applications/Audio2Caption
python script_run.py
/envs/paddlemax/lib/python3.10/site-packages/_distutils_hack/__init__.py:33：UserWarning：Setuptools 正在取代 distutils。
   warnings.warn("Setuptools 正在取代 distutils。")
分段錯誤（核心轉儲）

我已經使用了您的應用程式中的音訊字幕相同腳本的範例，但我遇到了錯誤。 您能幫我看看問題是什麼或如何解決嗎？

python script_run.py 
/envs/paddlemax/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Segmentation fault (core dumped)

I have used the example of audio captioning same script from your application, and I am facing the error. Would you be kind to help me what the issue is or how to resolve it?

**Comment by luyao-cv** [comment]
可以尝试下py38, cuda11.8环境。
