### ISSUE TITLE
sft全量微调多卡报错 

### ISSUE THREAD

**Issue by fangfangssj** [PaddlePaddle/PaddleMIX#577]
<img width="878" alt="c4ba535a46cf100854d633df508a21d" src="https://github.com/PaddlePaddle/PaddleMIX/assets/99968055/d62b0244-5438-46e1-becc-f91c3e9359c5">

环境使用的为paddle2.6.1docker镜像(nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6)，pip安装requirements.txt，硬件环境为nvidiaA100*4

多卡训练的时候会报错，但单卡训练的时候是正常的

**Comment by LokeZhou** [comment]
这种一般是显存不够
