### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by 1196228233** [PaddlePaddle/PaddleMIX#580]
File ~/external-libraries/ppdiffusers/utils/download_utils.py:34
     32 from filelock import FileLock
     33 from huggingface_hub import hf_hub_download, try_to_load_from_cache
---> 34 from huggingface_hub.file_download import _chmod_and_replace, http_get
     35 from huggingface_hub.utils import (
     36     EntryNotFoundError,
     37     RepositoryNotFoundError,
     38     RevisionNotFoundError,
     39 )
     40 from packaging import version

ImportError: cannot import name '_chmod_and_replace' from 'huggingface_hub.file_download'(/home/aistudio/external-libraries/huggingface_hub/file_download.py)

**Comment by nemonameless** [comment]
已修复在develop分支中，pip安装可能还是0.24.0旧版未修复的，可在编译安装：
```
git clone https://github.com/PaddlePaddle/PaddleMIX
cd PaddleMIX/ppdiffusers
python setup.py install
```
