### ISSUE TITLE
A import error and how i solve this problem?

### ISSUE THREAD

**Issue by ChYHENG123** [PaddlePaddle/PaddleMIX#590]
the detail error message is:

from ppdiffusers.utils import (
  File "E:\giteeproject\pythonProject\.venv\lib\site-packages\ppdiffusers\utils\__init__.py", line 72, in <module>
    from .download_utils import (
  File "E:\giteeproject\pythonProject\.venv\lib\site-packages\ppdiffusers\utils\download_utils.py", line 34, in <module>
    from huggingface_hub.file_download import _chmod_and_replace, http_get
ImportError: cannot import name '_chmod_and_replace' from 'huggingface_hub.file_download'

**Comment by nemonameless** [comment]
#580 #581

**Comment by MufanColin** [comment]
You can try this command: `pip install huggingface_hub==0.22`

> the detail error message is:
> 
> from ppdiffusers.utils import ( File "E:\giteeproject\pythonProject.venv\lib\site-packages\ppdiffusers\utils__init__.py", line 72, in from .download_utils import ( File "E:\giteeproject\pythonProject.venv\lib\site-packages\ppdiffusers\utils\download_utils.py", line 34, in from huggingface_hub.file_download import _chmod_and_replace, http_get ImportError: cannot import name '_chmod_and_replace' from 'huggingface_hub.file_download'
