### ISSUE TITLE
无法安装paddlenlp2.7.2

### ISSUE THREAD

**Issue by masaladi** [PaddlePaddle/PaddleMIX#673]
> 建议通过以下方式安装最新版paddlemix
> 
> ```
> git clone https://github.com/PaddlePaddle/PaddleMIX
> cd PaddleMIX
> pip install -e .
> 
> #ppdiffusers 安装
> cd ppdiffusers
> pip install -e .
> ```

请问下在安装ppdiffusers时报如下错需要如何解决呢，谢谢
#ppdiffusers 安装
cd ppdiffusers
pip install -e .
![image](https://github.com/user-attachments/assets/b84c11e1-02a0-4557-bf54-e5fb71584bda)

_Originally posted by @masaladi in https://github.com/PaddlePaddle/PaddleMIX/issues/645#issuecomment-2275297335_

**Comment by masaladi** [comment]
@lyuwenyu 我在PaddleNLP的项目中发现有人提了同样的问题，https://github.com/PaddlePaddle/PaddleNLP/issues/8344，是否可以参考修复此问题呢

**Comment by flymorn** [comment]
报错：
ERROR: Could not find a version that satisfies the requirement tool-helpers (from paddlenlp) (from versions: none)
ERROR: No matching distribution found for tool-helpers

解决方案：下载nlp源码，本地编译安装：

PaddleNLP/requirements.txt 里找到：
tool_helpers 
修改为：
tool_helpers ; platform_system == "Linux"
因为 tool_helpers 只有linux版本版本，没有windows版本，这里判断只在linux系统下需要即可。

然后编译安装：
cd PaddleNLP
pip install -e .

**Comment by masaladi** [comment]
> 报错： ERROR: Could not find a version that satisfies the requirement tool-helpers (from paddlenlp) (from versions: none) ERROR: No matching distribution found for tool-helpers
> 
> 解决方案：下载nlp源码，本地编译安装：
> 
> PaddleNLP/requirements.txt 里找到： tool_helpers 修改为： tool_helpers ; platform_system == "Linux" 因为 tool_helpers 只有linux版本版本，没有windows版本，这里判断只在linux系统下需要即可。
> 
> 然后编译安装： cd PaddleNLP pip install -e .

非常感谢你的回答，但是你的这个解决方案是PaddleNLP的，我是安装PaddleMIX时出的错，在PaddleMIX\ppdiffusers\requirements.txt源码里面也没有tool_helpers这个

**Comment by masaladi** [comment]
已找到解决方法：
将PaddleMIX\ppdiffusers\requirements.txt源码中paddlenlp==2.7.2的版本更换为paddlenlp==3.0.0b0 
问题暂时解决
