### ISSUE TITLE
PPDiffusers 0.24.1 Open-Sora 生成视频结果乱码 绿屏问题

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleMIX#707]
参考https://github.com/PaddlePaddle/PaddleMIX/tree/develop/ppdiffusers/examples/Open-Sora教程案例

在AI studio 复现一些测试脚本后，生成结果视频都是乱码绿屏

环境配置 ： V100 32G

复现命令(调整了总帧数，因为发现总帧数超过15，保存结果时，会爆显存：
PaddleMIX/ppdiffusers/examples/Open-Sora$ python scripts/inference.py --prompt "A beautiful sunset over the city" --num-frames 12 --image-size 256 256 

python scripts/inference-long.py --num-frames 13 --image-size 224 300 --sample-name connect --prompt 'A breathtaking sunrise scene.{"reference_path": "assets/images/condition/sunset1.png;assets/images/condition/sunset2.png","mask_strategy": "0;0,1,0,-1,1"}'

![image](https://github.com/user-attachments/assets/88d9a020-68ef-4ecb-9d45-25d3dc2bf4d8)

**Comment by westfish** [comment]
cv2保存的视频在部分播放器上有问题，正在修复，可以参考这个PR，https://github.com/PaddlePaddle/PaddleMIX/pull/712

**Comment by whisky-12** [comment]
辛苦了，目前使用的mac ，已验证上述情况，感谢反馈

再次感谢！

**Comment by whisky-12** [comment]
再次打扰了 ，我们现在框架所支持是否仅是Open-Sora 1.0的体系，目前默认生成视频只有 2 秒 ？ 没有发现其他可以控制输出视频时长的参数，由于显存的限制，目前32G一半生成帧数在13帧以下。

**Comment by whisky-12** [comment]
再次打扰了 ，我们现在框架所支持是否仅是Open-Sora 1.0的体系，目前默认生成视频只有 2 秒 ？ 没有发现其他可以控制输出视频时长的参数，由于显存的限制，目前32G一半生成帧数在13帧以下。

**Comment by westfish** [comment]
是的，目前仅支持opensora 1.0

**Comment by whisky-12** [comment]
我又来提问题了，当我尝试了openSora后，发现最终效果不满意后，尝试了 SVD 的方式生成视频，但我发现在管道执行后，先显存的资源没有被自然释放，导致我必须每次重启notebook来释放掉资源，还辛苦是否可以复现，并确定问题
![image](https://github.com/user-attachments/assets/49fe759e-e702-4d8b-a8f1-bfcc05bd6ee0)
