### ISSUE TITLE
测试运行失败

### ISSUE THREAD

**Issue by ruisunyc** [PaddlePaddle/PaddleMIX#802]
python paddlemix/examples/qwen2_vl/single_image_infer.py
![ebc2cf827accfff846c3507af028def0](https://github.com/user-attachments/assets/e6030624-64c2-40f1-aab6-31a95944fa9f)

<img width="792" alt="3e030c93bf832f8e222a504dcc793264" src="https://github.com/user-attachments/assets/c8c9d0f0-1581-473d-b2a4-e7a2b2b3ac33">

**Comment by luyao-cv** [comment]
感谢同学提供的问题，我们已经更新了说明，paddle需要develop版本，paddlenlp需要3.0.0b2 
请参考：https://github.com/PaddlePaddle/PaddleMIX/tree/develop/paddlemix/examples/qwen2_vl#readme
