### ISSUE TITLE
自制数据训练clip模型报错

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/PaddleMIX#804]
使用自制的数据，按照文档中要求的数据结构如下：
<img width="407" alt="image" src="https://github.com/user-attachments/assets/f6a08fbb-741d-411b-9c9f-bf07d1b288fd">
 在训练中 使用task_name 作为训练数据文件的路径带入，命令如下：
![image](https://github.com/user-attachments/assets/9c30598b-3979-447a-8db4-20d5ed1e9883)
报错如下：
![image](https://github.com/user-attachments/assets/7e5338fe-d9f4-463f-9d2d-b9c5bb0ae7d0)

有大佬能帮忙解决一下吗

**Comment by luyao-cv** [comment]
麻烦同学把最后一个反斜杠给去掉哈
![d275ee5ec471068584ec7f17840b9edb](https://github.com/user-attachments/assets/3d1bad12-ee10-4cc7-96ad-cea94ccfca02)

**Comment by lyuwenyu** [comment]
格式问题 这里也改了试一下；（ -> `--task_name ${task_name} \`

<img width="300" alt="image" src="https://github.com/user-attachments/assets/f8172370-c8c5-4989-9c1b-932fee616705">

---

可以多**注意看报错信息**以帮助定位问题
```
ValueError: Some specified arguments are not used by the PdArgumentParser: [
```

**Comment by luyao-cv** [comment]
参考修改：python -m paddle.distributed.launch --nproc_per_node 1 paddlemix/examples/clip/run_pretrain_dist.py \
--task_name "${task_name}" \
--dataloader_num_workers 2 \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 8 \
--model ${MODEL_NAME} \
--warmup_steps 2000 \
--learning_rate 5e-4 \
--weight_decay 0.05 \
--adam_beta1 0.9 \
--adam_beta2 0.999 \
--adam_epsilon 1e-8 \
--max_grad_norm 5.0 \
--num_train_epochs 200 \
--tensor_parallel_degree 1 \
--sharding_parallel_degree 8 \
--sharding "stage2" \
--bf16 False \
--output_dir "./output" \
--logging_steps 1 \
--do_train \
--disable_tqdm True \
--save_steps 50000 \
--local_loss true \
--gather_with_grad true \
--pretrained_text_model "CLIP-ViT-L-14-laion2B-s32B-b82K" \
--eval_classification_file '/home/aistudio/weapon-dataset-cls2/clip-anno.json'

**Comment by ericosmic** [comment]
> 参考修改：python -m paddle.distributed.launch --nproc_per_node 1 paddlemix/examples/clip/run_pretrain_dist.py --task_name "${task_name}" --dataloader_num_workers 2 --per_device_train_batch_size 16 --per_device_eval_batch_size 8 --model ${MODEL_NAME} --warmup_steps 2000 --learning_rate 5e-4 --weight_decay 0.05 --adam_beta1 0.9 --adam_beta2 0.999 --adam_epsilon 1e-8 --max_grad_norm 5.0 --num_train_epochs 200 --tensor_parallel_degree 1 --sharding_parallel_degree 8 --sharding "stage2" --bf16 False --output_dir "./output" --logging_steps 1 --do_train --disable_tqdm True --save_steps 50000 --local_loss true --gather_with_grad true --pretrained_text_model "CLIP-ViT-L-14-laion2B-s32B-b82K" --eval_classification_file '/home/aistudio/weapon-dataset-cls2/clip-anno.json'

谢谢 大佬😂
