### ISSUE TITLE
【PaddleMIX 热身打卡】跑通 Stable-Diffusion 训练报错

### ISSUE THREAD

**Issue by fxy1699** [PaddlePaddle/PaddleMIX#806]
#273 
ppdiffusers-0.29.0，安装方式为`python setup.py install`
在按照[文档](https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/stable_diffusion/README.md)对laion400数据集进行训练时运行train.sh脚本后报错`ValueError: Not supported value: 0`，查看对应源码`/home/aistudio/.local/lib/python3.10/site-packages/ppdiffusers-0.29.0-py3.10.egg/ppdiffusers/utils/constants.py`后，尝试修改train.sh环境变量值0为false，仍然报错。
train.sh如下
![image](https://github.com/user-attachments/assets/046a6fc0-27ad-4ee3-95c9-2fe6158f16e9)
报错如下：
![image](https://github.com/user-attachments/assets/5b48f364-6f32-40c9-9be4-ab95e28069d1)
`/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/aistudio/PaddleMIX/ppdiffusers/examples/stable_diffusion/train_txt2img_laion400m_trainer.py", line 21, in <module>
    from sd import (
  File "/home/aistudio/PaddleMIX/ppdiffusers/examples/stable_diffusion/sd/__init__.py", line 17, in <module>
    from .sd_args import SDDataArguments, SDModelArguments, SDTrainingArguments
  File "/home/aistudio/PaddleMIX/ppdiffusers/examples/stable_diffusion/sd/sd_args.py", line 31, in <module>
    if str2bool(os.getenv("FLAG_FUSED_LINEAR", "False")):
  File "/home/aistudio/.local/lib/python3.10/site-packages/ppdiffusers-0.29.0-py3.10.egg/ppdiffusers/utils/constants.py", line 30, in str2bool
    raise ValueError("Not supported value: {}".format(v))
ValueError: Not supported value: false`

**Comment by fxy1699** [comment]
`pip install ppdiffusers`也尝试过，是相同的错误

**Comment by luyao-cv** [comment]
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/requirements.txt 请使用ppdiffusion 0.23.0版本哈～0.29的太高啦

**Comment by fxy1699** [comment]
> https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/requirements.txt 请使用ppdiffusion 0.23.0版本哈～0.29的太高啦


没找到0.23.0版本的，切换到了0.24.0上述问题已经解决
`git checkout ppdiffusers0.24.0`
![image](https://github.com/user-attachments/assets/979db59e-5378-400c-82e0-2702600340f7)
在该branch下重新安装环境（aistudio停止后重新启动），在ppdiffusers目录下使用 `pip install -e .`安装环境，运行train.sh，报错如下：
![image](https://github.com/user-attachments/assets/542388c9-9660-42f9-9ba4-301938773c13)
huggingface-hub版本为0.23.4

**Comment by luyao-cv** [comment]
paddlenlp==v3.0.0-beta0
huggingface_hub==0.23.0
huggingface_hub降下版本，试下0.23和0.22哈。
