### ISSUE TITLE
PaddleMIX单机单卡训练stable diffusion无法读取环境变量

### ISSUE THREAD

**Issue by fxy1699** [PaddlePaddle/PaddleMIX#809]
@luyao-cv #806 #273 
基础环境：AI Studio  V100 32GB 单卡  cuda11.8
conda 环境：
python: 3.10.15
paddlepaddle-gpu：2.6.1（官网pip安装）
paddlenlp：2.7.2
ppdiffusers：0.24.1
![image](https://github.com/user-attachments/assets/85f63946-0a08-4e76-9eb8-b3bb65769aa7)

问题：按照stable diffusion [readme.md](https://github.com/PaddlePaddle/PaddleMIX/blob/ppdiffusers0.24.0/ppdiffusers/examples/stable_diffusion/README.md)中在路径 `~/PaddleMIX/ppdiffusers/examples/stable_diffusion` 新建单机单卡训练的脚本。
![image](https://github.com/user-attachments/assets/658731ac-bb41-42df-990d-d0ae348e1e13)
运行后会出现如下问题：（经测试ppdiffusers 0.24.0~0.29.0均会出现该问题，更低的环境未支持stable diffusion会有其他错）
![017b161ca3f43f75078920f3ccc1e72](https://github.com/user-attachments/assets/674bd892-bab8-4602-8aaf-05c44ad89ede)
经过反复验证，最终确认是无法读取train.sh中的环境变量（我根据源代码尝试将脚本中的0和1替代为true、false依然报错）

Readme中提供的单机单卡脚本如下：
![image](https://github.com/user-attachments/assets/9082454e-32e4-4ba7-bb5a-742a8e6389d4)

注释掉该部分环境变量后脚本可以正常运行：
![image](https://github.com/user-attachments/assets/89c47b83-2921-4bf0-bba5-68860cc7e033)
![image](https://github.com/user-attachments/assets/a57003ba-fe4e-4f1a-a3c5-a58fbd892b87)

注：多卡环境下能否读取环境变量没有条件进行测试，只测试了单机单卡环境。

**Comment by westfish** [comment]
https://github.com/PaddlePaddle/PaddleMIX/blob/0724380f2f94d32ef575f4ae9b5ae3b876cfb966/ppdiffusers/ppdiffusers/utils/constants.py#L27

在linux跑是没有你这里的报错的，正常来说"no", "false", "f", "n", "0"应该会被解析的，是不是没有处理好空格或着字符格式的问题呢

**Comment by fxy1699** [comment]
测试了一下应该是ai studio的问题，ai studio在运行脚本(utf-8编码)的时候识别不到换行符，同时也没法export环境变量。我做了以下对比实验：
1.train.sh不注释环境变量运行，使用echo命令无法找到相应变量，运行报错。
2.在~/.bashrc中手动添加环境变量并source，使用echo命令可以找到相应变量，同时train.sh注释掉环境变量，正常运行（此时相应的环境变量能被读取）。
3.在2的基础上，train.sh不注释环境变量，报错。

最后得到的结论是ai studio脚本的解析可能有点问题

**Comment by fxy1699** [comment]
破案了，aistudio的问题，aistudio里的主机环境没法在shell脚本里用export添加环境变量，但是在~/.bashrc可以添加这些环境变量
![image](https://github.com/user-attachments/assets/a03bdef5-42af-45f6-b1a2-cf9143528e32)
![image](https://github.com/user-attachments/assets/118689be-faea-498c-a8b2-ebdac46c5ed0)
