### ISSUE TITLE
[BUG] FileNotFoundError during evaluating Stable Diffusion

### ISSUE THREAD

**Issue by Albresky** [PaddlePaddle/PaddleMIX#858]
This bug can be recurrenced in the latest version of [PaddleMix](https://github.com/PaddlePaddle/PaddleMIX/tree/559ee9841f2ad879f3b1f8d861e91a2666d8e6e7/ppdiffusers/examples/stable_diffusion).

It happens on moving the temporarily downloaded params into `~/.cache/`:

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/mydir/.cache/paddlenlp/ppdiffusers/tmpg97lonv4' -> '/mydir/.cache/paddlenlp/ppdiffusers/CompVis/stable-diffusion-v1-4/feature_extractor/preprocessor_config.json'
```

This bug results from a bug in PaddleNLP, and I've attemped to fix it by PR: [Fix boe_download on non-exist directory #9565](https://github.com/PaddlePaddle/PaddleNLP/pull/9565).

**Comment by luyao-cv** [comment]
Hello, please provide the version  of paddlenlp you used. thank you very much.

**Comment by Albresky** [comment]
> Hello, please provide the version of paddlenlp you used. thank you very much.

Currently, the installed version is `paddlenlp==2.8.1`.

**Comment by Albresky** [comment]
This issue has been solved by upgrading paddlenlp to the 3.0.0-b2. https://github.com/PaddlePaddle/PaddleNLP/pull/9023 has fixed this issue.

**Comment by westfish** [comment]
Please install PaddleNLP version 3.0.0-beta2 by running the following command: pip install paddlenlp==3.0.0b2

**Comment by Albresky** [comment]
> Please install PaddleNLP version 3.0.0-beta2 by running the following command: pip install paddlenlp==3.0.0b2

Thx, this issue has been solved.
