### ISSUE TITLE
请问paddlemix 可以运行在win11上吗

### ISSUE THREAD

**Issue by itues** [PaddlePaddle/PaddleMIX#873]
我在win11上运行报错如下，不知道如何解决，请问是不能在win11 上运行吗？
![微信截图_20241211094833](https://github.com/user-attachments/assets/d87abf94-c545-4509-ae38-31e3bd29b84b)

**Comment by luyao-cv** [comment]
感谢关注，windows没有测试过，请移步linux测试开发，可在AISTUDIO上申请算力～
