### ISSUE TITLE
按照说明安装包括算子以后，仍然无法进行推理，说是需要paddlespeech

### ISSUE THREAD

**Issue by ChenControl** [PaddlePaddle/PaddleMIX#880]
直接用pip install paddlespeech会造成paddle降级，从3.0.0b2到2.5。在执行推理会出现各种错误。望解决。
<img width="764" alt="Snipaste_2024-12-16_14-47-44" src="https://github.com/user-attachments/assets/0f56b121-4b07-4d8b-b4d9-77ff2284195b" />
<img width="764" alt="Snipaste_2024-12-16_14-43-51" src="https://github.com/user-attachments/assets/6be94d82-cb8d-458f-ae52-c68f11bf3b19" />
<img width="764" alt="Snipaste_2024-12-16_14-31-59" src="https://github.com/user-attachments/assets/454237a9-1e77-41b2-8f4f-261451f1e17f" />
<img width="830" alt="Snipaste_2024-12-16_13-53-06" src="https://github.com/user-attachments/assets/d3f711e8-2c35-4793-8c7f-44f0123e69d7" />
<img width="764" alt="Snipaste_2024-12-16_13-52-49" src="https://github.com/user-attachments/assets/02ce0d12-c52c-440e-a1fc-d224104cb098" />
[MobaXterm_root@I1e4caef72c00b01e06hy-tmpPaddleMIX_20241216_145126.txt](https://github.com/user-attachments/files/18145399/MobaXterm_root%40I1e4caef72c00b01e06hy-tmpPaddleMIX_20241216_145126.txt)

**Comment by luyao-cv** [comment]
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/applications/README.md
appflow的应用需要按照这个部分安装依赖哈～
pip install -r paddlemix/appflow/requirements.txt
